import { GroupColors } from "./types";

export const DEFAULT_SERVICES: { name: string; price: number; group: string }[] = [
  { name: "A4 (B&W)", price: 5, group: "Printing" },
  { name: "A4 (Partial)", price: 7, group: "Printing" },
  { name: "A4 (Full Color)", price: 10, group: "Printing" },
  { name: "A4 on vellum (B&W)", price: 10, group: "Printing" },
  { name: "A4 on vellum (Partial)", price: 15, group: "Printing" },
  { name: "A4 on vellum (Full Color)", price: 20, group: "Printing" },
  { name: "Letter (B&W)", price: 5, group: "Printing" },
  { name: "Letter (Partial)", price: 7, group: "Printing" },
  { name: "Letter (Full Color)", price: 10, group: "Printing" },
  { name: "Long (B&W)", price: 6, group: "Printing" },
  { name: "Long (Partial)", price: 8, group: "Printing" },
  { name: "Long (Full Color)", price: 12, group: "Printing" },
  { name: "Back to back Add (B&W/Partial)", price: 2, group: "Printing" },
  { name: "Back to back Add (Full)", price: 5, group: "Printing" },
  { name: "A4 (B&W)", price: 4, group: "Xerox" },
  { name: "A4 (Partial)", price: 6, group: "Xerox" },
  { name: "A4 (Full Color)", price: 8, group: "Xerox" },
  { name: "Letter (B&W)", price: 4, group: "Xerox" },
  { name: "Letter (Partial)", price: 6, group: "Xerox" },
  { name: "Letter (Full Color)", price: 8, group: "Xerox" },
  { name: "Long (B&W)", price: 5, group: "Xerox" },
  { name: "Long (Partial)", price: 7, group: "Xerox" },
  { name: "Long (Full Color)", price: 10, group: "Xerox" },
  { name: "Back to back Add (B&W/Partial)", price: 2, group: "Xerox" },
  { name: "Back to back Add (Full)", price: 5, group: "Xerox" },
  { name: "P1 - 9pcs 1x1", price: 50, group: "Rush ID" },
  { name: "P2 - 9pcs 2x2", price: 50, group: "Rush ID" },
  { name: "P3 - 6pcs Passport", price: 50, group: "Rush ID" },
  { name: "P4 - 4pcs 2x2 & 6pcs 1x1", price: 60, group: "Rush ID" },
  { name: "P5 - 3pcs 2x2, Passport, & 4pcs 1x1", price: 70, group: "Rush ID" },
  { name: "P6 - 2pcs 2x2 & 4pcs 1x1", price: 40, group: "Rush ID" },
  { name: "P7 - 2pcs 2x3", price: 30, group: "Rush ID" },
  { name: "Add-on: Change Attire", price: 10, group: "Rush ID" },
  { name: "Add-on: Get Soft copy", price: 10, group: "Rush ID" },
  { name: "2R / Wallet Size", price: 15, group: "Photo" },
  { name: '3R (3.5" x 5")', price: 20, group: "Photo" },
  { name: '4R (4" x 6")', price: 30, group: "Photo" },
  { name: '5R (5" x 7")', price: 40, group: "Photo" },
  { name: '6R (6" x 8")', price: 50, group: "Photo" },
  { name: '8R (8" x 10")', price: 50, group: "Photo" },
  { name: "S8R / A4", price: 50, group: "Photo" },
  { name: "Laminate: 2R / Wallet", price: 20, group: "Laminate" },
  { name: "Laminate: 3R", price: 30, group: "Laminate" },
  { name: "Laminate: 4R", price: 40, group: "Laminate" },
  { name: "Laminate: 5R", price: 50, group: "Laminate" },
  { name: "Laminate: 6R", price: 60, group: "Laminate" },
  { name: "Laminate: 8R", price: 60, group: "Laminate" },
  { name: "Laminate: S8R / A4", price: 60, group: "Laminate" },
  { name: "PSA Online Appointment", price: 30, group: "Assistance" },
  { name: "PhilHealth Online Appointment", price: 30, group: "Assistance" },
  { name: "PAG_IBIG New Member", price: 50, group: "Assistance" },
  { name: "PAG_IBIG Generate and Print PRN", price: 30, group: "Assistance" },
  { name: "Brown Envelope (Short)", price: 6, group: "Stationery" },
  { name: "Brown Envelope (Long)", price: 8, group: "Stationery" },
  { name: "Plastic Envelope (Short)", price: 12, group: "Stationery" },
  { name: "Plastic Envelope (Long)", price: 15, group: "Stationery" },
  { name: "White Folder (Short)", price: 7, group: "Stationery" },
  { name: "White Folder (Long)", price: 10, group: "Stationery" },
  { name: "1/8 Illustration Board", price: 10, group: "Stationery" },
  { name: "Manila Paper", price: 8, group: "Stationery" },
  { name: "Intermediate Pad", price: 30, group: "Stationery" },
  { name: "Yellow Pad", price: 50, group: "Stationery" },
  { name: "Glue", price: 20, group: "Stationery" },
  { name: "Ballpen", price: 10, group: "Stationery" },
  { name: "Monggol 2 Pencil", price: 12, group: "Stationery" },
  { name: "HBW Marker Permanent", price: 20, group: "Stationery" },
  { name: "Sharpener", price: 5, group: "Stationery" },
  { name: "Fastener", price: 1, group: "Stationery" },
  { name: "Paper Clip 1 box", price: 18, group: "Stationery" },
  { name: "Double Sided tape", price: 26, group: "Stationery" },
  { name: "Scatch Tape 12mm", price: 10, group: "Stationery" },
  { name: "Scatch Tape 12mm (Big)", price: 26, group: "Stationery" },
  { name: "Scatch Tape 24mm", price: 30, group: "Stationery" },
  { name: "Scissors", price: 20, group: "Stationery" },
  { name: "HBW Correction Tape", price: 25, group: "Stationery" },
  { name: "Index Card 1/8 2pcs.", price: 1, group: "Stationery" },
  { name: "Index Card 1/4 1pc.", price: 1, group: "Stationery" },
  { name: "Index Card 1/2 1pc.", price: 2, group: "Stationery" },
  { name: "Assorted Colored Paper", price: 10, group: "Stationery" },
  { name: "Bond Paper (Short) 20pcs.", price: 10, group: "Stationery" },
  { name: "Bond Paper (A4) 20pcs.", price: 12, group: "Stationery" },
  { name: "Bond Paper (Long) 20pcs.", price: 15, group: "Stationery" },
  { name: "Oslo Paper 10pcs.", price: 10, group: "Stationery" },
  { name: "Clear Sliding Folder (Short)", price: 10, group: "Stationery" },
  { name: "Clear Sliding Folder (Long)", price: 12, group: "Stationery" },
  { name: "Bio-Data 1pc.", price: 2, group: "Stationery" },
  { name: "Quaff A4 Photo Paper 1pc.", price: 5, group: "Stationery" },
  { name: "Quaff A4 Photo Paper 1pack", price: 85, group: "Stationery" },
  { name: "ID lace", price: 15, group: "Stationery" },
  { name: "Ruler", price: 10, group: "Stationery" },
  { name: "Scan (Any size)", price: 10, group: "Scan" },
  { name: "Resume Typing Job", price: 50, group: "Other" },
  { name: "Name Tag", price: 50, group: "Other" },
  { name: "Name Tag with lace", price: 60, group: "Other" },
  { name: "A4 Name/Subjects Sticker label", price: 50, group: "Other" },
  { name: "Photo Editing Minor Enhancement", price: 30, group: "Other" },
  { name: "A4 1pc Laminating Film", price: 10, group: "Other" },
];

export const DEFAULT_GROUP_COLORS: GroupColors = {
  Printing: "#4A37AC",
  Xerox: "#B23568",
  "Rush ID": "#7E6BD8",
  Photo: "#B4650F",
  Laminate: "#0E9764",
  Scan: "#0891A8",
  Assistance: "#2A2065",
  Stationery: "#8A6D3B",
  Other: "#5B5560",
};
